<a href="https://colab.research.google.com/github/Alandlfp/Valores-Nulos/blob/main/Actividad_2(ValoresNulos).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
from google.colab import files
files.upload()

In [ ]:
data=pd.read_csv("inmuebles2.csv")
data.head(5)

,Unnamed: 0,Esta es una base de datos que describe las operaciones inmobiliarias de una empresa,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8
0,0,Referencia,Fecha Alta,Tipo,Operación,Provincia,Superficie,Precio Venta,Fecha Venta,Vendedor
1,1,1,2004-01-01 00:00:00,Parking,Alquiler,Lleida,291,2133903,2004-06-19 00:00:00,Carmen
2,2,2,2004-01-01 00:00:00,Local,Venta,Girona,185,1945424,2004-04-19 00:00:00,Pedro
3,3,3,2004-01-01 00:00:00,Oficina,Alquiler,Girona,82,NaN,2004-11-08 00:00:00,Joaquín
4,4,4,2004-01-02 00:00:00,Parking,Alquiler,Girona,285,NaN,2004-04-27 00:00:00,Jesús

In [ ]:
data1=pd.read_csv("inmuebles2.csv", skiprows=1)
data1

,0,Referencia,Fecha Alta,Tipo,Operación,Provincia,Superficie,Precio Venta,Fecha Venta,Vendedor
0,1,1,2004-01-01 00:00:00,Parking,Alquiler,Lleida,291.0,2133903.0,2004-06-19 00:00:00,Carmen
1,2,2,2004-01-01 00:00:00,Local,Venta,Girona,185.0,1945424.0,2004-04-19 00:00:00,Pedro
2,3,3,2004-01-01 00:00:00,Oficina,Alquiler,Girona,82.0,NaN,2004-11-08 00:00:00,Joaquín
3,4,4,2004-01-02 00:00:00,Parking,Alquiler,Girona,285.0,NaN,2004-04-27 00:00:00,Jesús
4,5,5,2004-01-02 00:00:00,Suelo,Venta,Tarragona,152.0,185000.0,2004-07-10 00:00:00,María
...,...,...,...,...,...,...,...,...,...,...
3332,3333,3333,2007-04-29 00:00:00,Industrial,Alquiler,Lleida,221.0,1450644.0,NaN,NaN
3333,3334,3334,2007-04-29 00:00:00,Piso,Alquiler,Girona,55.0,454080.0,NaN,NaN
3334,3335,3335,2007-04-30 00:00:00,Suelo,Venta,Tarragona,78.0,740688.0,NaN,NaN
3335,3336,3336,2007-04-30 00:00:00,Piso,Alquiler,Barcelona,88.0,397408.0,NaN,NaN
3336,3337,3337,2007-04-30 00:00:00,Parking,Venta,Lleida,NaN,2140712.0,NaN,NaN

In [ ]:
data2=data1.drop(['0', 'Referencia'], axis=1)
data2

,Fecha Alta,Tipo,Operación,Provincia,Superficie,Precio Venta,Fecha Venta,Vendedor
0,2004-01-01 00:00:00,Parking,Alquiler,Lleida,291.0,2133903.0,2004-06-19 00:00:00,Carmen
1,2004-01-01 00:00:00,Local,Venta,Girona,185.0,1945424.0,2004-04-19 00:00:00,Pedro
2,2004-01-01 00:00:00,Oficina,Alquiler,Girona,82.0,NaN,2004-11-08 00:00:00,Joaquín
3,2004-01-02 00:00:00,Parking,Alquiler,Girona,285.0,NaN,2004-04-27 00:00:00,Jesús
4,2004-01-02 00:00:00,Suelo,Venta,Tarragona,152.0,185000.0,2004-07-10 00:00:00,María
...,...,...,...,...,...,...,...,...
3332,2007-04-29 00:00:00,Industrial,Alquiler,Lleida,221.0,1450644.0,NaN,NaN
3333,2007-04-29 00:00:00,Piso,Alquiler,Girona,55.0,454080.0,NaN,NaN
3334,2007-04-30 00:00:00,Suelo,Venta,Tarragona,78.0,740688.0,NaN,NaN
3335,2007-04-30 00:00:00,Piso,Alquiler,Barcelona,88.0,397408.0,NaN,NaN
3336,2007-04-30 00:00:00,Parking,Venta,Lleida,NaN,2140712.0,NaN,NaN

In [ ]:
valores_nulos=data2.isnull().sum()
valores_nulos

Fecha Alta        2
Tipo              2
Operación         1
Provincia         4
Superficie        4
Precio Venta      6
Fecha Venta     578
Vendedor        578
dtype: int64

-*Metodo de sustitucion de valores nulos*

In [ ]:
data3=data2.copy()

In [ ]:
data3["Superficie"]=data3["Superficie"].fillna(round(data2["Superficie"].mean(),1))
data3

,Fecha Alta,Tipo,Operación,Provincia,Superficie,Precio Venta,Fecha Venta,Vendedor
0,2004-01-01 00:00:00,Parking,Alquiler,Lleida,291.0,2133903.0,2004-06-19 00:00:00,Carmen
1,2004-01-01 00:00:00,Local,Venta,Girona,185.0,1945424.0,2004-04-19 00:00:00,Pedro
2,2004-01-01 00:00:00,Oficina,Alquiler,Girona,82.0,NaN,2004-11-08 00:00:00,Joaquín
3,2004-01-02 00:00:00,Parking,Alquiler,Girona,285.0,NaN,2004-04-27 00:00:00,Jesús
4,2004-01-02 00:00:00,Suelo,Venta,Tarragona,152.0,185000.0,2004-07-10 00:00:00,María
...,...,...,...,...,...,...,...,...
3332,2007-04-29 00:00:00,Industrial,Alquiler,Lleida,221.0,1450644.0,NaN,NaN
3333,2007-04-29 00:00:00,Piso,Alquiler,Girona,55.0,454080.0,NaN,NaN
3334,2007-04-30 00:00:00,Suelo,Venta,Tarragona,78.0,740688.0,NaN,NaN
3335,2007-04-30 00:00:00,Piso,Alquiler,Barcelona,88.0,397408.0,NaN,NaN
3336,2007-04-30 00:00:00,Parking,Venta,Lleida,170.2,2140712.0,NaN,NaN

In [ ]:
valores_nulos=data3.isnull().sum()
valores_nulos

Fecha Alta        2
Tipo              2
Operación         1
Provincia         4
Superficie        0
Precio Venta      6
Fecha Venta     578
Vendedor        578
dtype: int64

In [ ]:
data3["Precio Venta"]=data3["Precio Venta"].fillna(round(data2["Precio Venta"].mean(),1))
data3

,Fecha Alta,Tipo,Operación,Provincia,Superficie,Precio Venta,Fecha Venta,Vendedor
0,2004-01-01 00:00:00,Parking,Alquiler,Lleida,291.0,2133903.0,2004-06-19 00:00:00,Carmen
1,2004-01-01 00:00:00,Local,Venta,Girona,185.0,1945424.0,2004-04-19 00:00:00,Pedro
2,2004-01-01 00:00:00,Oficina,Alquiler,Girona,82.0,1201918.3,2004-11-08 00:00:00,Joaquín
3,2004-01-02 00:00:00,Parking,Alquiler,Girona,285.0,1201918.3,2004-04-27 00:00:00,Jesús
4,2004-01-02 00:00:00,Suelo,Venta,Tarragona,152.0,185000.0,2004-07-10 00:00:00,María
...,...,...,...,...,...,...,...,...
3332,2007-04-29 00:00:00,Industrial,Alquiler,Lleida,221.0,1450644.0,NaN,NaN
3333,2007-04-29 00:00:00,Piso,Alquiler,Girona,55.0,454080.0,NaN,NaN
3334,2007-04-30 00:00:00,Suelo,Venta,Tarragona,78.0,740688.0,NaN,NaN
3335,2007-04-30 00:00:00,Piso,Alquiler,Barcelona,88.0,397408.0,NaN,NaN
3336,2007-04-30 00:00:00,Parking,Venta,Lleida,170.2,2140712.0,NaN,NaN

In [ ]:
valores_nulos=data3.isnull().sum()
valores_nulos

Fecha Alta        2
Tipo              2
Operación         1
Provincia         4
Superficie        0
Precio Venta      0
Fecha Venta     578
Vendedor        578
dtype: int64

In [ ]:
data3["Fecha Alta"]=data3["Fecha Alta"].fillna(10)
data3

,Fecha Alta,Tipo,Operación,Provincia,Superficie,Precio Venta,Fecha Venta,Vendedor
0,2004-01-01 00:00:00,Parking,Alquiler,Lleida,291.0,2133903.0,2004-06-19 00:00:00,Carmen
1,2004-01-01 00:00:00,Local,Venta,Girona,185.0,1945424.0,2004-04-19 00:00:00,Pedro
2,2004-01-01 00:00:00,Oficina,Alquiler,Girona,82.0,1201918.3,2004-11-08 00:00:00,Joaquín
3,2004-01-02 00:00:00,Parking,Alquiler,Girona,285.0,1201918.3,2004-04-27 00:00:00,Jesús
4,2004-01-02 00:00:00,Suelo,Venta,Tarragona,152.0,185000.0,2004-07-10 00:00:00,María
...,...,...,...,...,...,...,...,...
3332,2007-04-29 00:00:00,Industrial,Alquiler,Lleida,221.0,1450644.0,NaN,NaN
3333,2007-04-29 00:00:00,Piso,Alquiler,Girona,55.0,454080.0,NaN,NaN
3334,2007-04-30 00:00:00,Suelo,Venta,Tarragona,78.0,740688.0,NaN,NaN
3335,2007-04-30 00:00:00,Piso,Alquiler,Barcelona,88.0,397408.0,NaN,NaN
3336,2007-04-30 00:00:00,Parking,Venta,Lleida,170.2,2140712.0,NaN,NaN

In [ ]:
valores_nulos=data3.isnull().sum()
valores_nulos

Fecha Alta        0
Tipo              2
Operación         1
Provincia         4
Superficie        0
Precio Venta      0
Fecha Venta     578
Vendedor        578
dtype: int64

In [ ]:
data3["Fecha Venta"]=data3["Fecha Venta"].fillna("2030-06-19 00:00:00")
data3

,Fecha Alta,Tipo,Operación,Provincia,Superficie,Precio Venta,Fecha Venta,Vendedor
0,2004-01-01 00:00:00,Parking,Alquiler,Lleida,291.0,2133903.0,2004-06-19 00:00:00,Carmen
1,2004-01-01 00:00:00,Local,Venta,Girona,185.0,1945424.0,2004-04-19 00:00:00,Pedro
2,2004-01-01 00:00:00,Oficina,Alquiler,Girona,82.0,1201918.3,2004-11-08 00:00:00,Joaquín
3,2004-01-02 00:00:00,Parking,Alquiler,Girona,285.0,1201918.3,2004-04-27 00:00:00,Jesús
4,2004-01-02 00:00:00,Suelo,Venta,Tarragona,152.0,185000.0,2004-07-10 00:00:00,María
...,...,...,...,...,...,...,...,...
3332,2007-04-29 00:00:00,Industrial,Alquiler,Lleida,221.0,1450644.0,2030-06-19 00:00:00,NaN
3333,2007-04-29 00:00:00,Piso,Alquiler,Girona,55.0,454080.0,2030-06-19 00:00:00,NaN
3334,2007-04-30 00:00:00,Suelo,Venta,Tarragona,78.0,740688.0,2030-06-19 00:00:00,NaN
3335,2007-04-30 00:00:00,Piso,Alquiler,Barcelona,88.0,397408.0,2030-06-19 00:00:00,NaN
3336,2007-04-30 00:00:00,Parking,Venta,Lleida,170.2,2140712.0,2030-06-19 00:00:00,NaN

In [ ]:
valores_nulos=data3.isnull().sum()
valores_nulos

Fecha Alta        0
Tipo              2
Operación         1
Provincia         4
Superficie        0
Precio Venta      0
Fecha Venta       0
Vendedor        578
dtype: int64

In [ ]:
data3["Tipo"]=data3["Tipo"].fillna(method="ffill")
data3

,Fecha Alta,Tipo,Operación,Provincia,Superficie,Precio Venta,Fecha Venta,Vendedor
0,2004-01-01 00:00:00,Parking,Alquiler,Lleida,291.0,2133903.0,2004-06-19 00:00:00,Carmen
1,2004-01-01 00:00:00,Local,Venta,Girona,185.0,1945424.0,2004-04-19 00:00:00,Pedro
2,2004-01-01 00:00:00,Oficina,Alquiler,Girona,82.0,1201918.3,2004-11-08 00:00:00,Joaquín
3,2004-01-02 00:00:00,Parking,Alquiler,Girona,285.0,1201918.3,2004-04-27 00:00:00,Jesús
4,2004-01-02 00:00:00,Suelo,Venta,Tarragona,152.0,185000.0,2004-07-10 00:00:00,María
...,...,...,...,...,...,...,...,...
3332,2007-04-29 00:00:00,Industrial,Alquiler,Lleida,221.0,1450644.0,2030-06-19 00:00:00,NaN
3333,2007-04-29 00:00:00,Piso,Alquiler,Girona,55.0,454080.0,2030-06-19 00:00:00,NaN
3334,2007-04-30 00:00:00,Suelo,Venta,Tarragona,78.0,740688.0,2030-06-19 00:00:00,NaN
3335,2007-04-30 00:00:00,Piso,Alquiler,Barcelona,88.0,397408.0,2030-06-19 00:00:00,NaN
3336,2007-04-30 00:00:00,Parking,Venta,Lleida,170.2,2140712.0,2030-06-19 00:00:00,NaN

In [ ]:
valores_nulos=data3.isnull().sum()
valores_nulos

Fecha Alta        0
Tipo              0
Operación         1
Provincia         4
Superficie        0
Precio Venta      0
Fecha Venta       0
Vendedor        578
dtype: int64

In [ ]:
data3["Operación"]=data3["Operación"].fillna(method="bfill")
data3

,Fecha Alta,Tipo,Operación,Provincia,Superficie,Precio Venta,Fecha Venta,Vendedor
0,2004-01-01 00:00:00,Parking,Alquiler,Lleida,291.0,2133903.0,2004-06-19 00:00:00,Carmen
1,2004-01-01 00:00:00,Local,Venta,Girona,185.0,1945424.0,2004-04-19 00:00:00,Pedro
2,2004-01-01 00:00:00,Oficina,Alquiler,Girona,82.0,1201918.3,2004-11-08 00:00:00,Joaquín
3,2004-01-02 00:00:00,Parking,Alquiler,Girona,285.0,1201918.3,2004-04-27 00:00:00,Jesús
4,2004-01-02 00:00:00,Suelo,Venta,Tarragona,152.0,185000.0,2004-07-10 00:00:00,María
...,...,...,...,...,...,...,...,...
3332,2007-04-29 00:00:00,Industrial,Alquiler,Lleida,221.0,1450644.0,2030-06-19 00:00:00,NaN
3333,2007-04-29 00:00:00,Piso,Alquiler,Girona,55.0,454080.0,2030-06-19 00:00:00,NaN
3334,2007-04-30 00:00:00,Suelo,Venta,Tarragona,78.0,740688.0,2030-06-19 00:00:00,NaN
3335,2007-04-30 00:00:00,Piso,Alquiler,Barcelona,88.0,397408.0,2030-06-19 00:00:00,NaN
3336,2007-04-30 00:00:00,Parking,Venta,Lleida,170.2,2140712.0,2030-06-19 00:00:00,NaN

In [ ]:
valores_nulos=data3.isnull().sum()
valores_nulos

Fecha Alta        0
Tipo              0
Operación         0
Provincia         4
Superficie        0
Precio Venta      0
Fecha Venta       0
Vendedor        578
dtype: int64

In [ ]:
data3["Provincia"]=data3["Provincia"].fillna(method="bfill")
data3

,Fecha Alta,Tipo,Operación,Provincia,Superficie,Precio Venta,Fecha Venta,Vendedor
0,2004-01-01 00:00:00,Parking,Alquiler,Lleida,291.0,2133903.0,2004-06-19 00:00:00,Carmen
1,2004-01-01 00:00:00,Local,Venta,Girona,185.0,1945424.0,2004-04-19 00:00:00,Pedro
2,2004-01-01 00:00:00,Oficina,Alquiler,Girona,82.0,1201918.3,2004-11-08 00:00:00,Joaquín
3,2004-01-02 00:00:00,Parking,Alquiler,Girona,285.0,1201918.3,2004-04-27 00:00:00,Jesús
4,2004-01-02 00:00:00,Suelo,Venta,Tarragona,152.0,185000.0,2004-07-10 00:00:00,María
...,...,...,...,...,...,...,...,...
3332,2007-04-29 00:00:00,Industrial,Alquiler,Lleida,221.0,1450644.0,2030-06-19 00:00:00,NaN
3333,2007-04-29 00:00:00,Piso,Alquiler,Girona,55.0,454080.0,2030-06-19 00:00:00,NaN
3334,2007-04-30 00:00:00,Suelo,Venta,Tarragona,78.0,740688.0,2030-06-19 00:00:00,NaN
3335,2007-04-30 00:00:00,Piso,Alquiler,Barcelona,88.0,397408.0,2030-06-19 00:00:00,NaN
3336,2007-04-30 00:00:00,Parking,Venta,Lleida,170.2,2140712.0,2030-06-19 00:00:00,NaN

In [ ]:
valores_nulos=data3.isnull().sum()
valores_nulos

Fecha Alta      0
Tipo            0
Operación       0
Provincia       0
Superficie      0
Precio Venta    0
Fecha Venta     0
Vendedor        0
dtype: int64

In [ ]:
data3["Vendedor"]=data3["Vendedor"].fillna("2030-06-19 00:00:00")
data3

,Fecha Alta,Tipo,Operación,Provincia,Superficie,Precio Venta,Fecha Venta,Vendedor
0,2004-01-01 00:00:00,Parking,Alquiler,Lleida,291.0,2133903.0,2004-06-19 00:00:00,Carmen
1,2004-01-01 00:00:00,Local,Venta,Girona,185.0,1945424.0,2004-04-19 00:00:00,Pedro
2,2004-01-01 00:00:00,Oficina,Alquiler,Girona,82.0,1201918.3,2004-11-08 00:00:00,Joaquín
3,2004-01-02 00:00:00,Parking,Alquiler,Girona,285.0,1201918.3,2004-04-27 00:00:00,Jesús
4,2004-01-02 00:00:00,Suelo,Venta,Tarragona,152.0,185000.0,2004-07-10 00:00:00,María
...,...,...,...,...,...,...,...,...
3332,2007-04-29 00:00:00,Industrial,Alquiler,Lleida,221.0,1450644.0,2030-06-19 00:00:00,2030-06-19 00:00:00
3333,2007-04-29 00:00:00,Piso,Alquiler,Girona,55.0,454080.0,2030-06-19 00:00:00,2030-06-19 00:00:00
3334,2007-04-30 00:00:00,Suelo,Venta,Tarragona,78.0,740688.0,2030-06-19 00:00:00,2030-06-19 00:00:00
3335,2007-04-30 00:00:00,Piso,Alquiler,Barcelona,88.0,397408.0,2030-06-19 00:00:00,2030-06-19 00:00:00
3336,2007-04-30 00:00:00,Parking,Venta,Lleida,170.2,2140712.0,2030-06-19 00:00:00,2030-06-19 00:00:00

In [ ]:
valores_nulos=data3.isnull().sum().sum()
valores_nulos

0

*Metodo de eliminacion de valores nulos*

In [ ]:
valores_nulos=data2.isnull().sum()
valores_nulos

Fecha Alta        2
Tipo              2
Operación         1
Provincia         4
Superficie        4
Precio Venta      6
Fecha Venta     578
Vendedor        578
dtype: int64

In [ ]:
data4=data2.copy()

In [ ]:
data4=data2.dropna()
data4

,Fecha Alta,Tipo,Operación,Provincia,Superficie,Precio Venta,Fecha Venta,Vendedor
0,2004-01-01 00:00:00,Parking,Alquiler,Lleida,291.0,2133903.0,2004-06-19 00:00:00,Carmen
1,2004-01-01 00:00:00,Local,Venta,Girona,185.0,1945424.0,2004-04-19 00:00:00,Pedro
4,2004-01-02 00:00:00,Suelo,Venta,Tarragona,152.0,185000.0,2004-07-10 00:00:00,María
5,2004-01-03 00:00:00,Industrial,Alquiler,Girona,131.0,953156.0,2004-09-05 00:00:00,Pedro
7,2004-01-03 00:00:00,Oficina,Venta,Girona,235.0,2158475.0,2004-10-31 00:00:00,Jesús
...,...,...,...,...,...,...,...,...
3016,2006-12-30 00:00:00,Casa,Alquiler,Barcelona,264.0,1060488.0,2007-04-28 00:00:00,Joaquín
3017,2006-12-31 00:00:00,Oficina,Venta,Lleida,69.0,483828.0,2007-05-05 00:00:00,Pedro
3030,2007-01-07 00:00:00,Industrial,Alquiler,Lleida,196.0,904344.0,2007-04-20 00:00:00,Pedro
3042,2007-01-09 00:00:00,Local,Venta,Lleida,92.0,709596.0,2007-04-17 00:00:00,Carmen
3045,2007-01-10 00:00:00,Parking,Venta,Barcelona,233.0,1077858.0,2007-04-30 00:00:00,María

*Comparamos dataframe3(sustitucion) y dataframe4(eliminacion)*

In [ ]:
data3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3337 entries, 0 to 3336
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Fecha Alta    3337 non-null   object
 1   Tipo          3337 non-null   object
 2   Operación     3337 non-null   object
 3   Provincia     3337 non-null   object
 4   Superficie    3337 non-null   float64
 5   Precio Venta  3337 non-null   float64
 6   Fecha Venta   3337 non-null   object
 7   Vendedor      3337 non-null   object
dtypes: float64(2), object(6)
memory usage: 208.7+ KB

In [ ]:
data4.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2747 entries, 0 to 3045
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Fecha Alta    2747 non-null   object
 1   Tipo          2747 non-null   object
 2   Operación     2747 non-null   object
 3   Provincia     2747 non-null   object
 4   Superficie    2747 non-null   float64
 5   Precio Venta  2747 non-null   float64
 6   Fecha Venta   2747 non-null   object
 7   Vendedor      2747 non-null   object
dtypes: float64(2), object(6)
memory usage: 193.1+ KB

*Combertir dataset sin valores nulos a csv*

In [ ]:
data3.to_csv('inmuebles_sin_nulos.csv')

In [ ]:
files.download('inmuebles_sin_nulos.csv')